name: Get Epic Game
# test
on:
  # 每周五 UTC 时间 2:25 (中国时间周五 10：25)自动触发，使用前取消注释，即删除下面两行的前面的 #
  # 添加 master push pull 领取 可手动控制
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
    schedule:
      - cron: "25 2 * * 5"
      - cron: "25 2 * * 4"
    repository_dispatch: 
      types: epicgame

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Clone Claimer Repository
        uses: actions/checkout@v2
        with:
          repository: lingsamuel/epicgames-freebies-claimer
          ref: 'aa21c57d0ef19948a4f2864207173c86d5c0ffb7'
          path: workdir

      # 在 'Settings' - 'Secrets' 添加 EMAIL (你的 Epic 邮箱)，PASSWD (你的 Epic 密码)
      - name: Get Gifts
        uses: nick-invision/retry@v1
        with:
              timeout_minutes: 10
              max_attempts: 3
              command: |
                    cd workdir
                    npm install
                    node claimer unipittsburgh@gmail.com '${{ secrets.PASSWD }}' 0 '${{ secrets.SECRET0 }}'> games_up.info
      - name: Edit Games.info
        if: always()
        run: |
          cd workdir
          sed -i '1d' games_up.info
          sed -i 's/Successfully claimed/成功领取/' games_up.info
          sed -i 's/was already claimed for this account/已经领取/' games_up.info
          sed -i '$d' games_up.info
          date --rfc-3339=seconds >> ../games_up.info
          cat games_up.info >> ../games_up.info
          echo >> ../games_up.info
          
      - name: Get Gifts
        uses: nick-invision/retry@v1
        with:
              timeout_minutes: 10
              max_attempts: 3
              command: |
                    cd workdir
                    npm install
                    node claimer neo.george.caffrey@gmail.com '${{ secrets.PASSWD }}' 0 '${{ secrets.SECRET1 }}' > games_neo.info
      - name: Edit Games.info
        if: always()
        run: |
          cd workdir
          sed -i '1d' games_neo.info
          sed -i 's/Successfully claimed/成功领取/' games_neo.info
          sed -i 's/was already claimed for this account/已经领取/' games_neo.info
          sed -i '$d' games_neo.info
          date --rfc-3339=seconds >> ../games_neo.info
          cat games_neo.info >> ../games_neo.info
          echo >> ../games_neo.info
      - name: Get Gifts
        uses: nick-invision/retry@v1
        with:
              timeout_minutes: 10
              max_attempts: 3
              command: |
                    cd workdir
                    npm install
                    node claimer 267128979@qq.com '${{ secrets.PASSWD }}' 0 '${{ secrets.SECRET2 }}'> games_26.info
      - name: Edit Games.info
        if: always()
        run: |
          cd workdir
          sed -i '1d' games_26.info
          sed -i 's/Successfully claimed/成功领取/' games_26.info
          sed -i 's/was already claimed for this account/已经领取/' games_26.info
          sed -i '$d' games_26.info
          date --rfc-3339=seconds >> ../games_26.info
          cat games_26.info >> ../games_26.info
          echo >> ../games_26.info
      - name: Get Gifts
        uses: nick-invision/retry@v1
        with:
              timeout_minutes: 10
              max_attempts: 3
              command: |
                    cd workdir
                    npm install
                    node claimer caffrey_wu@163.com '${{ secrets.PASSWD }}' 0 '${{ secrets.SECRET3 }}'> games_ca.info
      - name: Edit Games.info
        if: always()
        run: |
          cd workdir
          sed -i '1d' games_ca.info
          sed -i 's/Successfully claimed/成功领取/' games_ca.info
          sed -i 's/was already claimed for this account/已经领取/' games_ca.info
          sed -i '$d' games_ca.info
          date --rfc-3339=seconds >> ../games_ca.info
          cat games_ca.info >> ../games_ca.info
          echo >> ../games_ca.info
      - name: Get Gifts
        uses: nick-invision/retry@v1
        with:
              timeout_minutes: 10
              max_attempts: 3
              command: |
                    cd workdir
                    npm install
                    node claimer qiw63@pitt.edu '${{ secrets.PASSWD }}' 0 '${{ secrets.SECRET4 }}'> games_qi.info
      - name: Edit Games.info
        if: always()
        run: |
          cd workdir
          sed -i '1d' games_qi.info
          sed -i 's/Successfully claimed/成功领取/' games_qi.info
          sed -i 's/was already claimed for this account/已经领取/' games_qi.info
          sed -i '$d' games_qi.info
          date --rfc-3339=seconds >> ../games_qi.info
          cat games_qi.info >> ../games_qi.info
          echo >> ../games_qi.info
      - name: Get Gifts
        uses: nick-invision/retry@v1
        with:
              timeout_minutes: 10
              max_attempts: 3
              command: |
                    cd workdir
                    npm install
                    node claimer qwuae@connect.ust.hk '${{ secrets.PASSWD }}' 0 '${{ secrets.SECRET5 }}'> games_qw.info
          


      - name: Edit Games.info
        if: always()
        run: |
          cd workdir
          sed -i '1d' games_qw.info
          sed -i 's/Successfully claimed/成功领取/' games_qw.info
          sed -i 's/was already claimed for this account/已经领取/' games_qw.info
          sed -i '$d' games_qw.info
          date --rfc-3339=seconds >> ../games_qw.info
          cat games_qw.info >> ../games_qw.info
          echo >> ../games_qw.info

      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m ":package: 领取游戏"
      # 此处的 ${{ secrets.GITHUB_TOKEN }} 是 Actions 自有变量，不用管
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        

      # 如果需要推送到 Telegram 用来提示，取消注释以下内容
      # 这部分的内容可以查看 https://www.github.com/appleboy/telegram-action
      # - name: Send Gift Info
      #   if: always()
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: "Chat ID"
      #     token: "TelegramBot 的 Token"
      #     format: markdown
      #     message_file: workdir/games.info
